export {default as AddressCard} from "./AddressCard"
export {default as OrdersTable} from "./OrdersTable"
export {default as OrderTableForSmallDevices} from "./OrderTableForSmallDevices"
export {default as PagesTitle} from "./PagesTitle"
export {default as ProfileNav} from "./ProfileNav"
export {default as SmallDevicesWishlistTable} from "./SmallDevicesWishlistTable"
export {default as WishlistItem} from "./WishlistItem"
export {default as WishlistTable} from "./WishlistTable"