import type { Metadata } from "next";
import React from "react";

type Props = {
  readonly children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

const layout = ({ children }: Props) => {
  return children;
};

export default layout;
